### ISSUE TITLE
chromebook 화면 깨짐 문제

### ISSUE THREAD

**Issue by holykss** [taehwandev/MediaProjectionExample#3]
안녕하세요.

올려주신 소스 잘 활용하고 있습니다.

크롬북에서 화면이 깨지고, 먹통이 되는 문제가 있는데요.

로그/영상 저장소: https://github.com/holykss-test/MediaProjectionExample/tree/fix/stride/doc

영상: https://photos.app.goo.gl/Tc4viqTVzGWbgf13A

동영상과 로그 넣어서 별도 브랜치에 올려두었습니다.

혹시 이 이슈에 대해 해결책이나 원인 등 정보가 있을지 궁금합니다.

감사합니다.

**Comment by taehwandev** [comment]
안녕하세요.
크롬북을 가지고 있지는 않고, 이전에 다른 분이 깨진다면서 PR 해주신게 있었습니다.
사용하시는 크롬북이 어떻게  될까요?
로그를 간단하게 보니 사이즈가 안맞아보이네요.

**Comment by holykss** [comment]
> 안녕하세요.
> 크롬북을 가지고 있지는 않고, 이전에 다른 분이 깨진다면서 PR 해주신게 있었습니다.
> 사용하시는 크롬북이 어떻게 될까요?
> 로그를 간단하게 보니 사이즈가 안맞아보이네요.

구글 픽셀북 고, 삼성 크롬북 프로 두 종으로 확인한 사항입니다. 이외 lenovo, poin2 2종 에선 문제가 없었습니다.

사이즈는 실기기와 동일하게 맞춰봐도 현상이 개선되지 않네요.

피드백 감사합니다.

**Comment by taehwandev** [comment]
사이즈가 동일하더라도 캡쳐하지 못하는 경우도 있습니다. 개발자  옵션에 있는 세컨 디스플레이 관련으로 실행해보시는것도 방법일것 같습니다.
